// Local, isolated demo verification. No paid providers or user data are used.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=path.resolve(__dirname,'../.validation');

async function run(){
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const errors=[],checks=[];
 const page=await browser.newPage({viewport:{width:1440,height:1080}});
 page.on('pageerror',e=>errors.push(e.message));
 const get=async(base,url)=>{const response=await page.request.get(base+url);assert(response.ok(),await response.text());return response.json()};
 try{
  const a='http://127.0.0.1:18971';
  await page.goto(a);await page.locator('#reader-workspace').waitFor();
  const before=await get(a,'/api/brainstorms');
  await page.locator('.rw-header [data-action="new"]').click();
  await page.locator('.idea-card').first().waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-idea-action="adopt"]')?.disabled);
  assert.equal(await page.locator('.idea-card').count(),4);
  assert.equal(await page.locator('.idea-start input[required],.idea-start textarea[required]').count(),0);
  assert(await page.locator('.idea-demo').isVisible());
  checks.push('A: zero-input new story shows four labelled ideas');
  await page.screenshot({path:path.join(output,'onboarding-a-desktop.png'),fullPage:true});
  let data=await get(a,'/api/brainstorms');const batch=data.batches[0];
  await page.reload();await page.locator('.rw-header [data-action="new"]').click();
  await page.locator('.idea-card').first().waitFor();
  assert.equal((await get(a,'/api/brainstorms')).batches.length,data.batches.length);
  checks.push('A: refresh reuses saved results');
  await page.locator('[data-idea-action="preferences"]').click();
  await page.locator('#f-preferences').fill('都市悬疑，少量人物');
  await page.locator('button[form="modal-form"]').click();
  await page.locator('select[name="idea-mode"]').selectOption('fast_drama');
  await page.locator('[data-idea-action="generate"]').click();
  await page.waitForFunction(()=>!document.querySelector('[data-idea-action="generate"]')?.disabled);
  data=await get(a,'/api/brainstorms');
  assert.notEqual(data.batches[0].id,batch.id);
  assert.equal(data.batches[0].mode,'fast_drama');
  assert.equal(data.batches[0].preferences,'都市悬疑，少量人物');
  const current=data.batches[0];
  await page.locator('[data-idea-action="explore"]').first().click();
  await page.waitForFunction(()=>!document.querySelector('[data-idea-action="explore"]')?.disabled);
  data=await get(a,'/api/brainstorms');
  assert.equal(data.batches[0].anchor.batchId,current.id);
  checks.push('A: preferences, reroll and anchored brainstorming work');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'onboarding-a-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  assert(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
  const oldAid=await page.locator('#reader-workspace').getAttribute('data-project');
  await page.locator('[data-idea-action="adopt"]').first().click();
  await page.locator('.modal-backdrop').waitFor({state:'hidden'});
  await page.waitForFunction(old=>document.querySelector('#reader-workspace')?.dataset.project!==old,oldAid);
  await page.locator('.rw-next').waitFor();
  assert.equal(await page.locator('.modal-backdrop').count(),0);
  const aid=await page.locator('#reader-workspace').getAttribute('data-project');
  const project=await get(a,'/api/projects/'+aid);
  assert.equal(project.project.ideaOrigin.batchId,data.batches[0].id);
  await page.locator('.rw-next [data-reader="advance"]').click();
  await page.locator('[data-reader="adopt"]').waitFor();
  checks.push('A: chosen idea creates project and continues directly to story candidates; mobile fits');

  const b='http://127.0.0.1:18972';
  await page.setViewportSize({width:1440,height:1080});
  await page.goto(b);await page.locator('.rw-header [data-action="new"]').click();
  assert.equal(await page.locator('#f-targetDuration,#f-budget').count(),0);
  assert.equal(await page.locator('#f-aspectRatio').inputValue(),'');
  const btitle='按内容规划 · '+Date.now();
  await page.locator('#f-title').fill(btitle);
  await page.locator('#f-source').fill('她推开门，停在门口。\n\n他说出失约的原因，把信递给她。她没有接，先问他为什么不早一点来。');
  await page.locator('#f-aspectRatio').selectOption('16:9');
  await page.locator('#f-preset').selectOption('cinema');
  assert.equal(await page.locator('#f-aspectRatio').inputValue(),'16:9');
  await page.screenshot({path:path.join(output,'onboarding-b-create.png'),fullPage:true});
  await page.locator('button[form="modal-form"]').click();
  await page.locator('.modal-backdrop').waitFor({state:'hidden'});
  await page.getByRole('heading',{name:btitle,exact:true}).waitFor();
  await page.locator('.rw-next').waitFor();
  const bid=await page.locator('#reader-workspace').getAttribute('data-project');
  let bp=await get(b,'/api/projects/'+bid);
  assert.equal(bp.style.aspectRatio,'16:9');assert.equal(bp.project.targetDuration,null);assert(!('budget' in bp.project));
  await page.locator('.rw-next [data-reader="advance"]').click();
  await page.locator('[data-reader="adopt"]').waitFor();
  assert((await page.locator('.rw-content').innerText()).includes('时长待节奏方案'));
  await page.locator('[data-reader="adopt"]').click();
  await page.locator('.rw-next [data-reader="advance"]').filter({hasText:'选择并确认全片视觉风格'}).waitFor();
  await page.locator('.rw-next [data-reader="advance"]').click();
  await page.locator('[data-action="choose-aspect"]').click();
  await page.locator('#f-aspectRatio').selectOption('1:1');
  await page.locator('button[form="modal-form"]').click();
  await page.waitForFunction(()=>!document.querySelector('.modal-backdrop'));
  await page.locator('.rw-proposal-part h3').filter({hasText:'1:1'}).waitFor();
  bp=await get(b,'/api/projects/'+bid);assert.equal(bp.style.aspectRatio,'1:1');
  await page.locator('[data-reader="finalize-style"]').click();
  await page.locator('.rw-next [data-reader="advance"]').filter({hasText:'设计改编与场次节奏'}).waitFor();
  await page.locator('.rw-next [data-reader="advance"]').click();
  await page.locator('[data-reader="adopt"]').waitFor();
  assert((await page.locator('.rw-content').innerText()).includes('建议本场'));
  await page.screenshot({path:path.join(output,'onboarding-b-timing.png'),fullPage:true});
  await page.locator('[data-reader="adopt"]').click();
  await page.locator('.rw-next [data-reader="advance"]').filter({hasText:'提取本场可复用视觉资产'}).waitFor();
  bp=await get(b,'/api/projects/'+bid);
  assert(bp.project.estimatedDuration>0);assert.equal(bp.project.targetDuration,null);
  checks.push('B: no upfront seconds/budget, independent chosen aspect, timing appears only after scene adaptation');
  // A later preset change must also preserve the selected aspect.
  await page.locator('[data-reader="advanced"]').first().click();
  await page.locator('[data-action="stage"][data-stage="B1"]').first().click();
  await page.locator('[data-action="preset"][data-key="series"]').click();
  await page.locator('[data-confirm]').click();
  await page.waitForFunction(()=>!document.querySelector('.modal-backdrop'));
  await page.locator('[data-action="preset"][data-key="series"]').filter({hasText:'当前风格'}).waitFor();
  bp=await get(b,'/api/projects/'+bid);assert.equal(bp.style.aspectRatio,'1:1');
  assert(!(await page.locator('.stage-rail').locator('..').innerText()).includes('媒体预算上限'));
  checks.push('B: applying another preset preserves selected aspect');
  await page.locator('[data-action="reader"]').first().click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'onboarding-b-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  checks.push('B: mobile layout fits');
  assert.deepEqual(errors,[]);
  const result={checks,errors,paidCalls:0,verifiedAt:new Date().toISOString()};
  fs.writeFileSync(path.join(output,'onboarding-browser-results.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
 } catch(error){
  await page.screenshot({path:path.join(output,'onboarding-failure.png'),fullPage:true});
  console.error('VISIBLE PAGE',await page.locator('body').innerText());
  throw error;
 } finally {await browser.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1});
