// Only against isolated demo servers. Never uses user production projects.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
async function main(){
 const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[];
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 const a='http://127.0.0.1:18851',b='http://127.0.0.1:18852';
 const headers={'x-studio-client':'local-ui'};
 fs.mkdirSync('.validation/upgrade-20260928',{recursive:true});
 try{
  await page.goto(a);await page.locator('#reader-workspace').waitFor();
  await page.locator('[data-studio="new-novel"]').click();
  await page.locator('#novel-create [name="title"]').fill('升级验收 · 开盒取物');
  await page.locator('#novel-file').setInputFiles({name:'测试小说.txt',mimeType:'text/plain',buffer:Buffer.from('第一章 开盒\n阿青把黑漆木盒放在桌上，掀开盒盖，露出一枚裂纹玉牌。她将玉牌递给老林，说：“别弄丢。”\n第二章 换装\n老林换上灰色外套，将玉牌收进内袋后离开仓库。')});
  const novelCreated=page.waitForResponse(r=>r.url()===`${a}/api/novels`&&r.request().method()==='POST');
  await page.locator('[form="novel-create"]').click();
  const novelResponse=await novelCreated;assert.ok(novelResponse.ok(),await novelResponse.text());
  const aId=(await novelResponse.json()).project.id;
  await page.waitForFunction(id=>document.querySelector('#rw-project')?.value===id,aId);
  await page.locator('[data-studio="draft-adopt"]').waitFor({timeout:30000});
  await page.screenshot({path:'.validation/upgrade-20260928/a-desktop.png',fullPage:true});
  const novelAdopted=page.waitForResponse(r=>r.url().includes(`/api/projects/${aId}/novel/drafts/`)&&r.url().endsWith('/adopt')&&r.request().method()==='POST');
  await page.locator('[data-studio="draft-adopt"]').click();
  const adoptionResponse=await novelAdopted;assert.ok(adoptionResponse.ok(),await adoptionResponse.text());
  await page.locator('[data-studio="draft-adopt"]').waitFor({state:'hidden'});
  const exported=await(await page.request.get(`${a}/api/projects/${aId}/export/scene-export`)).json();
  assert.equal(exported.schemaVersion,4);assert.ok(exported.storyDocument.continuity.events.length);
  assert.ok(exported.analysisCoverage.complete);assert.ok(exported.knowledgeSnapshot);
  fs.mkdirSync('.validation/upgrade-20260928',{recursive:true});
  fs.writeFileSync('.validation/upgrade-20260928/handoff-v4.json',JSON.stringify(exported,null,2));
  await page.locator('[data-reader="memory"]').click();await page.locator('[data-memory-add]').click();
  await page.locator('#f-text').fill('快节奏短剧需要尽早进入冲突，但不要影响电影版的留白。');
  await page.locator('#f-category').selectOption('preference');await page.locator('[form="modal-form"]').click();
  await page.getByRole('heading',{name:'反馈与记忆'}).waitFor();assert.ok(await page.getByText('快节奏短剧需要尽早进入冲突，但不要影响电影版的留白。',{exact:true}).count());
  await page.locator('[data-close]').click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.validation/upgrade-20260928/a-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'A mobile overflow');
  await page.goto(b);await page.setViewportSize({width:1440,height:1000});
  await page.locator('.rw-header [data-action="new"]').click();
  await page.locator('#f-title').fill('升级验收 · B 双版本');await page.locator('#f-aspectRatio').selectOption('16:9');
  const projectCreated=page.waitForResponse(r=>r.url()===`${b}/api/projects`&&r.request().method()==='POST');
  await page.locator('[form="modal-form"]').click();
  const projectResponse=await projectCreated;assert.ok(projectResponse.ok(),await projectResponse.text());
  const bId=(await projectResponse.json()).project.id;
  await page.waitForFunction(id=>document.querySelector('#rw-project')?.value===id,bId);
  await page.locator('.rw-next').waitFor();
  let response=await page.request.post(`${b}/api/projects/${bId}/import-scene-export`,{data:exported,headers});assert.ok(response.ok(),await response.text());
  await page.reload();await page.locator('[data-studio="convert"]').first().click();
  await page.locator('#f-mode').selectOption('cinema');await page.locator('[form="modal-form"]').click();
  await page.locator('[data-studio="draft-adopt"]').waitFor({timeout:20000});
  await page.screenshot({path:'.validation/upgrade-20260928/b-shooting-desktop.png',fullPage:true});
  const filmAdopted=page.waitForResponse(r=>r.url().includes(`/api/projects/${bId}/shooting/`)&&r.url().endsWith('/adopt')&&r.request().method()==='POST');
  await page.locator('[data-studio="draft-adopt-next"]').click();await page.locator('[data-confirm]').click();assert.ok((await filmAdopted).ok());
  await page.locator('[data-reader="adopt"]').waitFor({timeout:20000});
  const directorAdopted=page.waitForResponse(r=>r.url().includes(`/api/projects/${bId}/proposals/`)&&r.url().endsWith('/adopt')&&r.request().method()==='POST');
  await page.locator('[data-reader="adopt"]').click();await page.locator('[data-confirm]').click();assert.ok((await directorAdopted).ok());
  await page.locator('.rw-shot').waitFor();
  let data=await(await page.request.get(`${b}/api/projects/${bId}`)).json();
  const cinemaId=data.project.activeShootingId;assert.equal(data.project.presentationMode,'cinema');assert.ok(data.shots.length);
  await page.locator('[data-studio="convert"]').first().click();await page.locator('#f-mode').selectOption('fast_drama');await page.locator('[form="modal-form"]').click();
  await page.locator('[data-studio="draft-adopt"]').waitFor({timeout:20000});
  data=await(await page.request.get(`${b}/api/projects/${bId}`)).json();assert.equal(data.project.activeShootingId,cinemaId);assert.equal(data.shooting_scripts.length,2);
  const fastAdopted=page.waitForResponse(r=>r.url().includes(`/api/projects/${bId}/shooting/`)&&r.url().endsWith('/adopt')&&r.request().method()==='POST');
  await page.locator('[data-studio="draft-adopt"]').click();await page.locator('[data-confirm]').click();assert.ok((await fastAdopted).ok());
  await page.waitForFunction(()=>document.querySelector('.studio-bar')?.textContent.includes('呈现：快节奏短剧'));
  data=await(await page.request.get(`${b}/api/projects/${bId}`)).json();assert.notEqual(data.project.activeShootingId,cinemaId);
  await page.locator('[data-studio="shooting"]').click();
  await page.waitForTimeout(6500);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.validation/upgrade-20260928/b-shooting-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'B mobile overflow');
  await page.locator('[data-reader="assets"]').click();await page.screenshot({path:'.validation/upgrade-20260928/b-assets-mobile.png',fullPage:true});
  response=await page.request.put(`${b}/api/settings`,{headers,data:{media:{provider:'demo'}}});assert.ok(response.ok());
  await page.locator('[data-reader="finalize-style"]').click();await page.locator('[data-reader="finalize-style"]').waitFor({state:'hidden'});
  await page.locator('[data-studio="reference-generate"]').first().click();await page.locator('[data-confirm]').click();
  await page.locator('#f-evidence').waitFor({timeout:20000});await page.locator('#f-evidence').fill('浏览器验收使用的本地测试卡，仅验证文件、核对和采用链路。');await page.locator('#f-confirmed').check();
  const imageReviewed=page.waitForResponse(r=>r.url().endsWith('/review-reference')&&r.request().method()==='POST');
  await page.locator('[form="modal-form"]').click();assert.ok((await imageReviewed).ok());await page.locator('.studio-asset img').waitFor();
  await page.locator('[data-studio="make-tasks"]').click();await page.locator('[form="modal-form"]').click();await page.getByText('生成单元已准备',{exact:true}).waitFor();await page.keyboard.press('Escape');
  await page.locator('[data-studio="task-render"]').first().click();await page.locator('[data-confirm]').click();await page.getByRole('button',{name:'标定镜头区间',exact:true}).waitFor({timeout:20000});
  await page.getByRole('button',{name:'标定镜头区间',exact:true}).click();await page.locator('#f-in_0').waitFor();
  await page.waitForFunction(()=>Number.isFinite(document.querySelector('.modal video')?.duration));
  const actualDuration=await page.locator('.modal video').evaluate(v=>v.duration);
  await page.locator('#f-out_0').fill((Math.floor(actualDuration*1000)/1000).toFixed(3));
  const unitImported=page.waitForResponse(r=>r.url().includes('/generation-tasks/')&&r.url().endsWith('/import')&&r.request().method()==='POST');
  await page.locator('[form="modal-form"]').click();assert.ok((await unitImported).ok());
  data=await(await page.request.get(`${b}/api/projects/${bId}`)).json();assert.ok(data.renders.some(r=>r.proposedInterval&&!r.selected));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'B media mobile overflow');
  await page.locator('[data-studio="production"]').last().click();await page.locator('#render-kind').selectOption('clip');
  await page.locator('[data-action="select-render"]').first().click();await page.locator('#f-observationEvidence').fill('演示验收视频的采用区间末态，仅作为工程流程测试依据。');await page.locator('#f-confirmExpectedEndState').check();
  const videoAdopted=page.waitForResponse(r=>r.url().includes('/renders/')&&r.url().endsWith('/review')&&r.request().method()==='POST');
  await page.locator('[form="modal-form"]').click();const videoResponse=await videoAdopted;assert.ok(videoResponse.ok(),await videoResponse.text());
  await page.getByRole('button',{name:'已终选',exact:true}).waitFor();
  data=await(await page.request.get(`${b}/api/projects/${bId}`)).json();assert.ok(data.renders.some(r=>r.selected&&r.adoption?.interval&&r.adoption?.observation?.evidence));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'B review mobile overflow');await page.screenshot({path:'.validation/upgrade-20260928/b-review-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.validation/upgrade-20260928/b-review-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);
  const result={passed:true,aProject:aId,bProject:bId,checks:['TXT ingestion and full-book analysis','novel adoption','SceneExport v4','natural-language experience capture','film and fast drama version isolation','automatic assets/director choice','shot adoption','reference fee preview and explicit adoption','generation unit fee preview and interval import','actual video interval and end-state adoption','390px no overflow','no browser errors'],mediaGenerated:'local demo image and video only',paidCalls:false};
  fs.writeFileSync('.validation/upgrade-20260928/browser-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 }finally{await browser.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1});
